# Please fill out with content

version: '3.6'

services:
  gateway:
    image: eedu/gateway
    container_name: eedu-gateway
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: SECRET
      SERVICE_SECRET: SECRET
      PRODUCTIVE: "false"
