# Please fill out with content

version: '3.6'

services:
  task:
    image: eedu/gateway
    container_name: eedu-gateway
    restart: never
    ports:
      - 80:80
    environment:
      JWT_SECRET: SECRET
      SERVICE_SECRET: SECRET
      PRODUCTIVE: "false"
