# Please fill out with content

version: '3.6'

services:
  gateway:
    image: eedu/gateway
    container_name: eedu-gateway
    ports:
      - 80:80
    environment:
      JWT_SECRET: SECRET
      SERVICE_SECRET: SECRET
      PRODUCTIVE: "false"
      SENTRY_ENABLED: "${SENTRY_ENABLED}"
