name: Checkstyle

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - run: chmod 755 gradlew
      - run: ./gradlew checkstyleMain
